---
type: default
team: # need from consumer
group: # need from consumer
service: jvm-threaddump

# The environment container image is used to prepare code versions
# and tooling for tests during pre, post and build stages.
environment_image:
  file: ".acquia/Dockerfile.ci"
  context: "."
  args: ""
  build_args:
    - secrets:
      - type: vault
        key: SSH_KEY
        value: GIT_SSH_KEY
        path: secret/pipeline-default/GIT_SSH_KEY


pre_build:
  gradlew assemble:
    - steps:
        - /bin/bash -l -c "./gradlew assemble"

build:
  service_image:
    - name: acquia/jvm-threaddump
      file: "Dockerfile"
      context: "."
