---
type: default
team: bucc
group: content-cloud
service: jvm-threaddump

# While debugging validate the formatting of this pipeline.yaml file.
validate_config: true

# The environment container image is used to prepare code versions
# and tooling for tests during pre, post and build stages.
environment_image:
  file: ".acquia/Dockerfile.ci"
  context: "."
  args: ""

pre_build:
  code_analysis:
    required: false
  gradlew assemble:
    - steps:
      - ""

build:
  service_package:
    - type: maven
      pattern: '*.jar'
      props:
        - maintainer=widen

deploy:
    dev:
      # check_health: true # Enable Health Check on acd deployment (Default: false)
      # timeout: 3         # Maximum timeout 3 minutes for the acd command (Default: 5 minutes)
    qa:
      # check_health: false
      # timeout: 5
    staging:
      # check_health: true # Enable Health Check on acd deployment
      # timeout: 5
    prod:
      # check_health: true
      # timeout: 5